# Setup
title:        Reactive Microsolutions
tagline:      Software engineering and consulting services
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Constantine Sterpis
  url:        http://reactive-microsolutions.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown